# Generated by Django 5.1.3 on 2025-01-12 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_remove_user_avatar_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='points.class'),
        ),
    ]
