# Generated by Django 5.1.3 on 2025-01-13 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_user_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='department',
        ),
    ]
